[package]
name = "core"
version = "0.1.0"
authors = ["Martin Carltoft <martin@bitbleep.com>"]
edition = "2018"

[dependencies]
rt-core = { path = "../rt-core" }
probe-rs = "0.8.0"
colored = "2"
structopt = "0.3.18"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = "1.0.116"
