[package]
name = "emt"
version = "0.1.0"
authors = ["Martin Carltoft <martin@bitbleep.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
probe-rs = "0.8.0"
colored = "2"
structopt = "0.3.18"
