[package]
name = "emt-host"
version = "0.1.0"
authors = ["Martin <martin@bitbleep.com>"]
edition = "2018"

[dependencies]
emt = { path = "../emt" }
structopt = "0.3.18"
serde = "1.0.116"
actix-web = "3"
