[package]
name = "emt-host"
version = "0.1.0"
authors = ["Martin <martin@bitbleep.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
serde = "1.0.116"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
